pp counter by me
l3lackShark/static pull request #30
Opened 2021-11-06 13:34 UTC by nikzz-tea

2022-08-17 13:23 UTC, Dartandr requested changes
1) we can't approve second counter because it isn't an original creation
2) you need to add your counter to readme

2022-08-17 13:23 UTC, Dartandr commented on nikzzCounter/index.js
> +let sb = document.getElementsByClassName('sb');
it's better approach to use getElementById() to avoid ppC[0]

2022-09-08 15:33 UTC, nikzz-tea commented
deleted first one, renamed second one to Gradiental, updated readme

2022-09-08 18:31 UTC, Dartandr commented
You probably miss understood but we can't approve counter that you leaved 
![image](https://user-images.githubusercontent.com/32641958/189198437-f65e6393-c1ae-42b9-aa1d-a67b87b81eca.png)

2022-09-10 16:20 UTC, nikzz-tea commented
oh i just didnt see the word "second" 
im just gonna close then cuz dont really wanna add first one anymore sorry

2022-09-10 16:20 UTC, closed without merging